name: pipeline

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build WASM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Run tests
      run: cargo test --verbose
    - run: wasm-pack build --target web
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: curve-webapp
        path: |
          pkg
          www
  publish:
    name: Publish to alwaysgone.github.io
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: curve-webapp